version: "3.8"
services:
    api:
        container_name: prueba_siroko
        hostname: prueba_siroko
        build: .
        ports: 
            - 80:80
        volumes:
            - .:/var/www/html/prueba_siroko
            - ./.docker/php/conf.d:/usr/local/etc/php/conf.d
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - db
        networks:
            - prueba_siroko_api
            - prueba_siroko_db

    db:
        image: mysql:8.0
        container_name: prueba_siroko_db
        hostname: prueba_siroko_db
        ports: 
            - 3306:3306
        # command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: prueba_siroko
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./.docker/mysql/entrypoint:/docker-entrypoint-initdb.d
        #     - ./mysql/conf.d:/etc/mysql/conf.d
        #     - persistent:/var/lib/mysql
        networks:
            - prueba_siroko_db

    rabbitmq:
        image: rabbitmq:management-alpine
        container_name: prueba_siroko_rabbitmq
        hostname: prueba_siroko_rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - prueba_siroko_api
    
    # redis:
    #     image: redis:latest
    #     container_name: mo2o-redis
    #     restart: always
    #     ports:
    #       - 6379:6379
    #     command: redis-server --save 20 1 --loglevel warning --requirepass test
    #     networks:
    #         - default
    
    prueba_siroko-phpmyadmin:
        container_name: prueba_siroko_phpmyadmin
        hostname: prueba_siroko_phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - 8000:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        depends_on:
            - db
        networks:
            - prueba_siroko_db

networks:
    prueba_siroko_api:
        name: prueba_siroko_api
        driver: bridge

    prueba_siroko_db:
        name: prueba_siroko_db
        driver: bridge

volumes:
    persistent:
