# controllers:
#     resource:
#         path: ../src/Controller/
#         namespace: App\Controller
#     type: attribute

user_authentication:
    path:       /sign-in
    controller: App\Entrypoint\Controller\Dashboard\Authentication\SignInController
    methods:    POST

google_user_authentication:
    path:       /google-sign-in
    controller: App\Entrypoint\Controller\Dashboard\Authentication\GoogleSignInController
    methods:    POST

register_user:
    path:       /user
    controller: App\Entrypoint\Controller\Dashboard\User\ApplicationRegisterUserController
    methods:    POST